Name: volctrain-training
Host: 0.0.0.0
Port: 8891
Timeout: 30

# 数据库配置
MySQL:
  Host: mysql
  Port: 3306
  User: root
  Password: root
  DBName: volctraindb
  Charset: utf8mb4
  ParseTime: true
  Loc: "Asia/Shanghai"
  MaxOpenConns: 100
  MaxIdleConns: 10
  MaxLifetime: 3600

# Redis配置  
Redis:
  Host: redis
  Port: 6379
  Password: ""
  DB: 0
  PoolSize: 100
  MinIdleConns: 10

# 日志配置
Log:
  ServiceName: volctrain-training
  Mode: console
  Level: info

# JWT配置
Auth:
  AccessSecret: volctrain_access_secret_key_minimum_64_characters_required_security
  AccessExpire: 86400
  RefreshExpire: 604800

# 监控配置
Prometheus:
  Host: 0.0.0.0
  Port: 9090
  Path: /metrics

# 训练服务特定配置
Training:
  MaxConcurrentJobs: 10
  JobTimeoutSeconds: 3600
  CheckpointInterval: 300
  ResourceMonitorInterval: 30
  GPUAllocationStrategy: "balanced"
