-- 文件存储表
CREATE TABLE vt_files (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    original_name VARCHAR(256) NOT NULL COMMENT '原始文件名',
    file_name VARCHAR(256) NOT NULL COMMENT '存储文件名',
    file_path VARCHAR(512) NOT NULL COMMENT '文件路径',
    file_size BIGINT NOT NULL COMMENT '文件大小(字节)',
    mime_type VARCHAR(128) COMMENT 'MIME类型',
    file_extension VARCHAR(16) COMMENT '文件扩展名',
    file_hash VARCHAR(128) COMMENT '文件哈希值',
    checksum VARCHAR(128) COMMENT '校验和',
    storage_type ENUM('local', 's3', 'oss', 'minio', 'hdfs') DEFAULT 'local' COMMENT '存储类型',
    storage_config JSON COMMENT '存储配置',
    bucket_name VARCHAR(128) COMMENT '存储桶名称',
    file_category ENUM(
        'image',
        'document',
        'video',
        'audio',
        'archive',
        'code',
        'model',
        'dataset',
        'other'
    ) DEFAULT 'other' COMMENT '文件类别',
    upload_status ENUM('uploading', 'completed', 'failed', 'deleted') DEFAULT 'uploading' COMMENT '上传状态',
    is_public TINYINT(1) DEFAULT 0 COMMENT '是否公开',
    download_count INT DEFAULT 0 COMMENT '下载次数',
    virus_scan_status ENUM(
        'pending',
        'clean',
        'infected',
        'error',
        'skipped'
    ) DEFAULT 'pending' COMMENT '病毒扫描状态',
    virus_scan_result JSON COMMENT '病毒扫描结果',
    compression_type ENUM('none', 'gzip', 'zip', 'tar') DEFAULT 'none' COMMENT '压缩类型',
    metadata JSON COMMENT '文件元数据',
    tags JSON COMMENT '标签',
    expire_at TIMESTAMP NULL COMMENT '过期时间',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at TIMESTAMP NULL COMMENT '软删除时间',
    INDEX idx_file_name (file_name),
    INDEX idx_file_hash (file_hash),
    INDEX idx_storage_type (storage_type),
    INDEX idx_file_category (file_category),
    INDEX idx_upload_status (upload_status),
    INDEX idx_created_at (created_at),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_expire_at (expire_at),
    INDEX idx_category_status (file_category, upload_status),
    INDEX idx_hash_size (file_hash, file_size)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '文件存储表';
-- 文件访问记录表
CREATE TABLE vt_file_access_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    file_id BIGINT NOT NULL COMMENT '文件ID',
    user_id BIGINT COMMENT '用户ID',
    workspace_id BIGINT COMMENT '工作空间ID',
    action_type ENUM(
        'upload',
        'download',
        'view',
        'delete',
        'copy',
        'move'
    ) NOT NULL COMMENT '操作类型',
    access_ip VARCHAR(64) COMMENT '访问IP',
    user_agent TEXT COMMENT '用户代理',
    file_size BIGINT COMMENT '文件大小',
    transfer_duration_ms INT COMMENT '传输时长(毫秒)',
    status ENUM('success', 'failed', 'partial') DEFAULT 'success' COMMENT '操作状态',
    error_message TEXT COMMENT '错误信息',
    metadata JSON COMMENT '元数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_file_id (file_id),
    INDEX idx_user_id (user_id),
    INDEX idx_workspace_id (workspace_id),
    INDEX idx_action_type (action_type),
    INDEX idx_created_at (created_at),
    INDEX idx_file_action (file_id, action_type),
    INDEX idx_user_action (user_id, action_type)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '文件访问记录表';
-- 文件关联关系表 (通用关联表，替代各种外键关系)
CREATE TABLE vt_file_relations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    file_id BIGINT NOT NULL COMMENT '文件ID',
    entity_type VARCHAR(64) NOT NULL COMMENT '实体类型(user, workspace, dataset, model等)',
    entity_id BIGINT NOT NULL COMMENT '实体ID',
    relation_type VARCHAR(64) NOT NULL COMMENT '关联类型(avatar, attachment, model_file, dataset_file等)',
    workspace_id BIGINT COMMENT '所属工作空间ID',
    owner_id BIGINT COMMENT '拥有者ID',
    is_primary TINYINT(1) DEFAULT 0 COMMENT '是否主要文件',
    sort_order INT DEFAULT 0 COMMENT '排序',
    status ENUM('active', 'inactive', 'pending', 'deleted') DEFAULT 'active' COMMENT '状态',
    metadata JSON COMMENT '元数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_file_entity_relation (file_id, entity_type, entity_id, relation_type),
    INDEX idx_file_id (file_id),
    INDEX idx_entity (entity_type, entity_id),
    INDEX idx_relation_type (relation_type),
    INDEX idx_workspace_id (workspace_id),
    INDEX idx_owner_id (owner_id),
    INDEX idx_status (status),
    INDEX idx_entity_relation (entity_type, relation_type)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '文件关联关系表';