-- 工作空间表
CREATE TABLE vt_workspaces (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL COMMENT '工作空间名称',
    display_name VARCHAR(256) COMMENT '显示名称',
    description TEXT COMMENT '工作空间描述',
    workspace_type ENUM('personal', 'team', 'organization', 'project') DEFAULT 'team' COMMENT '工作空间类型',
    visibility ENUM('public', 'private', 'internal') DEFAULT 'private' COMMENT '可见性',
    storage_quota_gb DECIMAL(10, 2) DEFAULT 100.00 COMMENT '存储配额(GB)',
    compute_quota_hours DECIMAL(10, 2) DEFAULT 1000.00 COMMENT '计算配额(小时)',
    gpu_quota_hours DECIMAL(10, 2) DEFAULT 100.00 COMMENT 'GPU配额(小时)',
    dataset_quota_count INT DEFAULT 100 COMMENT '数据集配额数量',
    model_quota_count INT DEFAULT 50 COMMENT '模型配额数量',
    member_quota_count INT DEFAULT 20 COMMENT '成员配额数量',
    storage_used_gb DECIMAL(10, 2) DEFAULT 0.00 COMMENT '已用存储(GB)',
    compute_used_hours DECIMAL(10, 2) DEFAULT 0.00 COMMENT '已用计算(小时)',
    gpu_used_hours DECIMAL(10, 2) DEFAULT 0.00 COMMENT '已用GPU(小时)',
    dataset_count INT DEFAULT 0 COMMENT '数据集数量',
    model_count INT DEFAULT 0 COMMENT '模型数量',
    member_count INT DEFAULT 0 COMMENT '成员数量',
    status ENUM('active', 'inactive', 'suspended', 'archived') DEFAULT 'active' COMMENT '状态',
    features_enabled JSON COMMENT '启用的功能列表',
    settings JSON COMMENT '工作空间设置',
    default_permissions JSON COMMENT '默认权限配置',
    billing_type ENUM('free', 'subscription', 'pay_as_go') DEFAULT 'free' COMMENT '计费类型',
    billing_config JSON COMMENT '计费配置',
    tags JSON COMMENT '标签',
    metadata JSON COMMENT '元数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at TIMESTAMP NULL COMMENT '软删除时间',
    last_activity_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '最后活动时间',
    UNIQUE KEY uk_name (name),
    INDEX idx_workspace_type (workspace_type),
    INDEX idx_visibility (visibility),
    INDEX idx_status (status),
    INDEX idx_billing_type (billing_type),
    INDEX idx_created_at (created_at),
    INDEX idx_deleted_at (deleted_at),
    INDEX idx_last_activity_at (last_activity_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '工作空间表';
-- 工作空间成员表
CREATE TABLE vt_workspace_members (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    workspace_id BIGINT NOT NULL COMMENT '工作空间ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    role ENUM('owner', 'admin', 'member', 'viewer', 'guest') DEFAULT 'member' COMMENT '成员角色',
    invited_by BIGINT COMMENT '邀请人ID',
    invited_at TIMESTAMP NULL COMMENT '邀请时间',
    invitation_token VARCHAR(128) COMMENT '邀请令牌',
    invitation_message TEXT COMMENT '邀请消息',
    invitation_expires_at TIMESTAMP NULL COMMENT '邀请过期时间',
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
    last_activity_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '最后活动时间',
    status ENUM(
        'active',
        'inactive',
        'pending',
        'rejected',
        'removed'
    ) DEFAULT 'pending' COMMENT '成员状态',
    custom_permissions JSON COMMENT '自定义权限',
    resource_limits JSON COMMENT '资源限制',
    notification_settings JSON COMMENT '通知设置',
    metadata JSON COMMENT '元数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_workspace_user (workspace_id, user_id),
    INDEX idx_workspace_id (workspace_id),
    INDEX idx_user_id (user_id),
    INDEX idx_role (role),
    INDEX idx_status (status),
    INDEX idx_invited_by (invited_by),
    INDEX idx_invitation_token (invitation_token),
    INDEX idx_invitation_expires_at (invitation_expires_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '工作空间成员表';
-- 工作空间项目表
CREATE TABLE vt_workspace_projects (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    workspace_id BIGINT NOT NULL COMMENT '工作空间ID',
    name VARCHAR(128) NOT NULL COMMENT '项目名称',
    display_name VARCHAR(256) COMMENT '显示名称',
    description TEXT COMMENT '项目描述',
    project_type ENUM(
        'ml_training',
        'data_analysis',
        'model_serving',
        'research',
        'experiment',
        'custom'
    ) DEFAULT 'ml_training' COMMENT '项目类型',
    repository_url VARCHAR(512) COMMENT '代码仓库URL',
    storage_used_gb DECIMAL(10, 2) DEFAULT 0.00 COMMENT '已用存储(GB)',
    compute_used_hours DECIMAL(10, 2) DEFAULT 0.00 COMMENT '已用计算(小时)',
    gpu_used_hours DECIMAL(10, 2) DEFAULT 0.00 COMMENT '已用GPU(小时)',
    status ENUM('active', 'inactive', 'completed', 'archived') DEFAULT 'active' COMMENT '项目状态',
    visibility ENUM('public', 'private', 'workspace') DEFAULT 'workspace' COMMENT '可见性',
    priority ENUM('low', 'normal', 'high', 'urgent') DEFAULT 'normal' COMMENT '优先级',
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
    planned_end_at TIMESTAMP NULL COMMENT '计划结束时间',
    completed_at TIMESTAMP NULL COMMENT '完成时间',
    last_activity_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '最后活动时间',
    tags JSON COMMENT '标签',
    metadata JSON COMMENT '元数据',
    settings JSON COMMENT '项目设置',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at TIMESTAMP NULL COMMENT '软删除时间',
    UNIQUE KEY uk_workspace_project_name (workspace_id, name),
    INDEX idx_workspace_id (workspace_id),
    INDEX idx_project_type (project_type),
    INDEX idx_status (status),
    INDEX idx_visibility (visibility),
    INDEX idx_priority (priority),
    INDEX idx_created_at (created_at),
    INDEX idx_deleted_at (deleted_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '工作空间项目表';
-- 工作空间所有者关联表
CREATE TABLE vt_workspace_owners (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    workspace_id BIGINT NOT NULL COMMENT '工作空间ID',
    user_id BIGINT NOT NULL COMMENT '所有者用户ID',
    owner_type ENUM('primary', 'co_owner') DEFAULT 'primary' COMMENT '所有者类型',
    start_date DATE COMMENT '开始日期',
    end_date DATE COMMENT '结束日期',
    status ENUM('active', 'inactive') DEFAULT 'active' COMMENT '状态',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_workspace_user_type (workspace_id, user_id, owner_type),
    INDEX idx_workspace_id (workspace_id),
    INDEX idx_user_id (user_id),
    INDEX idx_owner_type (owner_type),
    INDEX idx_status (status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '工作空间所有者关联表';
-- 项目所有者关联表
CREATE TABLE vt_project_owners (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    project_id BIGINT NOT NULL COMMENT '项目ID',
    user_id BIGINT NOT NULL COMMENT '所有者用户ID',
    owner_type ENUM('primary', 'co_owner') DEFAULT 'primary' COMMENT '所有者类型',
    start_date DATE COMMENT '开始日期',
    end_date DATE COMMENT '结束日期',
    status ENUM('active', 'inactive') DEFAULT 'active' COMMENT '状态',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_project_user_type (project_id, user_id, owner_type),
    INDEX idx_project_id (project_id),
    INDEX idx_user_id (user_id),
    INDEX idx_owner_type (owner_type),
    INDEX idx_status (status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '项目所有者关联表';