-- GPU集群表
CREATE TABLE vt_gpu_clusters (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL COMMENT '集群名称',
    display_name VARCHAR(256) COMMENT '显示名称',
    description TEXT COMMENT '集群描述',
    cluster_type ENUM('k8s', 'slurm', 'yarn', 'standalone') DEFAULT 'k8s' COMMENT '集群类型',
    cluster_endpoint VARCHAR(512) COMMENT '集群端点',
    cluster_config JSON COMMENT '集群配置',
    total_nodes INT DEFAULT 0 COMMENT '总节点数',
    available_nodes INT DEFAULT 0 COMMENT '可用节点数',
    total_gpus INT DEFAULT 0 COMMENT '总GPU数',
    available_gpus INT DEFAULT 0 COMMENT '可用GPU数',
    region VARCHAR(64) COMMENT '区域',
    zone VARCHAR(64) COMMENT '可用区',
    datacenter VARCHAR(128) COMMENT '数据中心',
    status ENUM('active', 'inactive', 'maintenance', 'error') DEFAULT 'active' COMMENT '集群状态',
    health_status ENUM('healthy', 'warning', 'critical', 'unknown') DEFAULT 'unknown' COMMENT '健康状态',
    last_heartbeat_at TIMESTAMP NULL COMMENT '最后心跳时间',
    cpu_usage_percent DECIMAL(5, 2) DEFAULT 0 COMMENT '集群CPU使用率',
    memory_usage_percent DECIMAL(5, 2) DEFAULT 0 COMMENT '集群内存使用率',
    gpu_usage_percent DECIMAL(5, 2) DEFAULT 0 COMMENT '集群GPU使用率',
    tags JSON COMMENT '标签',
    metadata JSON COMMENT '元数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at TIMESTAMP NULL COMMENT '软删除时间',
    UNIQUE KEY uk_name (name),
    INDEX idx_cluster_type (cluster_type),
    INDEX idx_region_zone (region, zone),
    INDEX idx_status (status),
    INDEX idx_health_status (health_status),
    INDEX idx_deleted_at (deleted_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'GPU集群表';
-- GPU节点表
CREATE TABLE vt_gpu_nodes (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL COMMENT '节点名称',
    hostname VARCHAR(256) NOT NULL COMMENT '主机名',
    ip_address VARCHAR(64) NOT NULL COMMENT 'IP地址',
    node_type ENUM('physical', 'virtual', 'cloud') DEFAULT 'physical' COMMENT '节点类型',
    os_type VARCHAR(64) COMMENT '操作系统类型',
    os_version VARCHAR(64) COMMENT '操作系统版本',
    architecture VARCHAR(32) COMMENT '架构(x86_64, arm64等)',
    kernel_version VARCHAR(128) COMMENT '内核版本',
    cpu_model VARCHAR(256) COMMENT 'CPU型号',
    cpu_cores INT COMMENT 'CPU核心数',
    cpu_threads INT COMMENT 'CPU线程数',
    memory_gb INT COMMENT '内存大小(GB)',
    storage_gb INT COMMENT '存储大小(GB)',
    network_bandwidth_mbps INT COMMENT '网络带宽(Mbps)',
    gpu_count INT DEFAULT 0 COMMENT 'GPU数量',
    gpu_total_memory_gb DECIMAL(8, 2) DEFAULT 0 COMMENT 'GPU总显存(GB)',
    status ENUM(
        'online',
        'offline',
        'maintenance',
        'error',
        'draining'
    ) DEFAULT 'offline' COMMENT '节点状态',
    health_status ENUM('healthy', 'warning', 'critical', 'unknown') DEFAULT 'unknown' COMMENT '健康状态',
    schedulable TINYINT(1) DEFAULT 1 COMMENT '是否可调度',
    last_heartbeat_at TIMESTAMP NULL COMMENT '最后心跳时间',
    boot_time TIMESTAMP NULL COMMENT '启动时间',
    cpu_usage_percent DECIMAL(5, 2) DEFAULT 0 COMMENT 'CPU使用率',
    memory_usage_percent DECIMAL(5, 2) DEFAULT 0 COMMENT '内存使用率',
    storage_usage_percent DECIMAL(5, 2) DEFAULT 0 COMMENT '存储使用率',
    network_usage_mbps DECIMAL(10, 2) DEFAULT 0 COMMENT '网络使用率(Mbps)',
    temperature_celsius DECIMAL(5, 2) COMMENT '温度(摄氏度)',
    load_average_1m DECIMAL(5, 2) COMMENT '1分钟负载',
    load_average_5m DECIMAL(5, 2) COMMENT '5分钟负载',
    load_average_15m DECIMAL(5, 2) COMMENT '15分钟负载',
    allocatable_cpu_cores DECIMAL(6, 3) COMMENT '可分配CPU核心数',
    allocatable_memory_gb DECIMAL(8, 2) COMMENT '可分配内存(GB)',
    allocatable_gpu_count INT DEFAULT 0 COMMENT '可分配GPU数量',
    node_group VARCHAR(128) COMMENT '节点组',
    labels JSON COMMENT 'K8s标签',
    annotations JSON COMMENT 'K8s注解',
    taints JSON COMMENT 'K8s污点',
    tags JSON COMMENT '标签',
    metadata JSON COMMENT '元数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at TIMESTAMP NULL COMMENT '软删除时间',
    UNIQUE KEY uk_hostname (hostname),
    UNIQUE KEY uk_ip_address (ip_address),
    INDEX idx_name (name),
    INDEX idx_node_type (node_type),
    INDEX idx_status (status),
    INDEX idx_health_status (health_status),
    INDEX idx_schedulable (schedulable),
    INDEX idx_node_group (node_group),
    INDEX idx_deleted_at (deleted_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'GPU节点表';
-- GPU设备表
CREATE TABLE vt_gpu_devices (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    device_name VARCHAR(128) NOT NULL COMMENT '设备名称',
    device_index INT NOT NULL COMMENT '设备索引',
    device_uuid VARCHAR(128) COMMENT '设备UUID',
    pci_bus_id VARCHAR(32) COMMENT 'PCI总线ID',
    minor_number INT COMMENT '设备号',
    k8s_resource_name VARCHAR(255) COMMENT 'K8s资源名称',
    k8s_node_name VARCHAR(255) COMMENT 'K8s节点名称',
    gpu_model VARCHAR(128) COMMENT 'GPU型号',
    gpu_brand ENUM('nvidia', 'amd', 'intel', 'other') DEFAULT 'nvidia' COMMENT 'GPU品牌',
    architecture VARCHAR(64) COMMENT 'GPU架构',
    cuda_version VARCHAR(32) COMMENT 'CUDA版本',
    driver_version VARCHAR(32) COMMENT '驱动版本',
    vbios_version VARCHAR(64) COMMENT 'VBIOS版本',
    mig_enabled TINYINT(1) DEFAULT 0 COMMENT '是否启用MIG',
    mig_devices JSON COMMENT 'MIG设备列表',
    memory_total_mb INT COMMENT '显存总量(MB)',
    memory_free_mb INT COMMENT '可用显存(MB)',
    memory_used_mb INT COMMENT '已用显存(MB)',
    core_count INT COMMENT '核心数',
    sm_count INT COMMENT 'SM数量',
    base_clock_mhz INT COMMENT '基础频率(MHz)',
    boost_clock_mhz INT COMMENT '加速频率(MHz)',
    memory_clock_mhz INT COMMENT '显存频率(MHz)',
    memory_bus_width INT COMMENT '显存位宽',
    compute_capability VARCHAR(16) COMMENT '计算能力',
    max_power_limit_watts INT COMMENT '最大功耗限制(瓦)',
    status ENUM(
        'available',
        'occupied',
        'reserved',
        'maintenance',
        'error',
        'offline'
    ) DEFAULT 'available' COMMENT '设备状态',
    health_status ENUM('healthy', 'warning', 'critical', 'unknown') DEFAULT 'unknown' COMMENT '健康状态',
    utilization_percent DECIMAL(5, 2) DEFAULT 0 COMMENT 'GPU使用率',
    memory_utilization_percent DECIMAL(5, 2) DEFAULT 0 COMMENT '显存使用率',
    encoder_utilization_percent DECIMAL(5, 2) DEFAULT 0 COMMENT '编码器使用率',
    decoder_utilization_percent DECIMAL(5, 2) DEFAULT 0 COMMENT '解码器使用率',
    temperature_celsius DECIMAL(5, 2) COMMENT '温度(摄氏度)',
    power_usage_watts DECIMAL(7, 2) COMMENT '功耗(瓦)',
    power_limit_watts DECIMAL(7, 2) COMMENT '功耗限制(瓦)',
    fan_speed_percent DECIMAL(5, 2) COMMENT '风扇转速百分比',
    fan_speed_rpm INT COMMENT '风扇转速(RPM)',
    performance_state VARCHAR(16) COMMENT '性能状态(P0-P12)',
    gpu_mode ENUM('normal', 'compute', 'graphics') DEFAULT 'normal' COMMENT 'GPU模式',
    multi_gpu_board TINYINT(1) DEFAULT 0 COMMENT '是否多GPU板卡',
    board_id INT COMMENT '板卡ID',
    capabilities JSON COMMENT '设备能力',
    metadata JSON COMMENT '元数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_device_uuid (device_uuid),
    INDEX idx_device_name (device_name),
    INDEX idx_gpu_model (gpu_model),
    INDEX idx_gpu_brand (gpu_brand),
    INDEX idx_status (status),
    INDEX idx_health_status (health_status),
    INDEX idx_k8s_node_name (k8s_node_name)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'GPU设备表';
-- GPU使用记录表
CREATE TABLE vt_gpu_usage_records (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_type ENUM(
        'training',
        'inference',
        'development',
        'testing'
    ) COMMENT '任务类型',
    started_at TIMESTAMP NOT NULL COMMENT '开始时间',
    ended_at TIMESTAMP NULL COMMENT '结束时间',
    duration_seconds INT COMMENT '使用时长(秒)',
    avg_utilization_percent DECIMAL(5, 2) COMMENT '平均GPU使用率',
    max_utilization_percent DECIMAL(5, 2) COMMENT '最大GPU使用率',
    avg_memory_utilization_percent DECIMAL(5, 2) COMMENT '平均显存使用率',
    max_memory_utilization_percent DECIMAL(5, 2) COMMENT '最大显存使用率',
    avg_power_usage_watts DECIMAL(7, 2) COMMENT '平均功耗(瓦)',
    max_power_usage_watts DECIMAL(7, 2) COMMENT '最大功耗(瓦)',
    peak_temperature_celsius DECIMAL(5, 2) COMMENT '峰值温度(摄氏度)',
    compute_units DECIMAL(12, 6) COMMENT '计算单元',
    cost_amount DECIMAL(10, 4) COMMENT '费用金额',
    billing_mode ENUM('hourly', 'per_task', 'monthly') DEFAULT 'hourly' COMMENT '计费模式',
    status ENUM('running', 'completed', 'failed', 'cancelled') DEFAULT 'running' COMMENT '记录状态',
    metadata JSON COMMENT '元数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_started_at (started_at),
    INDEX idx_ended_at (ended_at),
    INDEX idx_status (status),
    INDEX idx_task_type (task_type)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'GPU使用记录表';
-- GPU集群节点关联表
CREATE TABLE vt_gpu_cluster_nodes (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    cluster_id BIGINT NOT NULL COMMENT '集群ID',
    node_id BIGINT NOT NULL COMMENT '节点ID',
    join_date DATE COMMENT '加入日期',
    leave_date DATE COMMENT '离开日期',
    node_role ENUM('master', 'worker', 'edge') DEFAULT 'worker' COMMENT '节点角色',
    status ENUM('active', 'inactive', 'draining') DEFAULT 'active' COMMENT '状态',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_cluster_node (cluster_id, node_id),
    INDEX idx_cluster_id (cluster_id),
    INDEX idx_node_id (node_id),
    INDEX idx_node_role (node_role),
    INDEX idx_status (status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'GPU集群节点关联表';
-- GPU节点设备关联表
CREATE TABLE vt_gpu_node_devices (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    node_id BIGINT NOT NULL COMMENT '节点ID',
    device_id BIGINT NOT NULL COMMENT '设备ID',
    device_index INT NOT NULL COMMENT '设备在节点上的索引',
    mount_path VARCHAR(256) COMMENT '挂载路径',
    status ENUM('active', 'inactive', 'error') DEFAULT 'active' COMMENT '状态',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_node_device (node_id, device_id),
    UNIQUE KEY uk_node_device_index (node_id, device_index),
    INDEX idx_node_id (node_id),
    INDEX idx_device_id (device_id),
    INDEX idx_status (status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'GPU节点设备关联表';
-- GPU设备分配关联表 (替代当前使用者的外键关系)
CREATE TABLE vt_gpu_device_allocations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    device_id BIGINT NOT NULL COMMENT '设备ID',
    entity_type VARCHAR(64) NOT NULL COMMENT '实体类型(user, workspace, training_job等)',
    entity_id BIGINT NOT NULL COMMENT '实体ID',
    allocation_type VARCHAR(64) DEFAULT 'exclusive' COMMENT '分配类型(exclusive, shared)',
    allocated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '分配时间',
    released_at TIMESTAMP NULL COMMENT '释放时间',
    expected_duration_seconds INT COMMENT '预期使用时长(秒)',
    priority INT DEFAULT 0 COMMENT '优先级',
    status ENUM(
        'pending',
        'active',
        'releasing',
        'released',
        'expired'
    ) DEFAULT 'pending' COMMENT '分配状态',
    metadata JSON COMMENT '元数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_device_id (device_id),
    INDEX idx_entity (entity_type, entity_id),
    INDEX idx_allocation_type (allocation_type),
    INDEX idx_allocated_at (allocated_at),
    INDEX idx_status (status),
    INDEX idx_device_status (device_id, status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'GPU设备分配关联表';
-- GPU使用记录关联表 (将使用记录与相关实体关联)
CREATE TABLE vt_gpu_usage_relations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    usage_record_id BIGINT NOT NULL COMMENT 'GPU使用记录ID',
    entity_type VARCHAR(64) NOT NULL COMMENT '实体类型(gpu_device, user, workspace, task等)',
    entity_id BIGINT NOT NULL COMMENT '实体ID',
    relation_type VARCHAR(64) NOT NULL COMMENT '关联类型(device, user, workspace, task等)',
    metadata JSON COMMENT '元数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UNIQUE KEY uk_usage_entity_relation (
        usage_record_id,
        entity_type,
        entity_id,
        relation_type
    ),
    INDEX idx_usage_record_id (usage_record_id),
    INDEX idx_entity (entity_type, entity_id),
    INDEX idx_relation_type (relation_type),
    INDEX idx_entity_relation (entity_type, relation_type)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'GPU使用记录关联表';