// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	api2 "github.com/GoSimplicity/VolcTrain/internal/system/api"
	"github.com/GoSimplicity/VolcTrain/internal/system/dao"
	"github.com/GoSimplicity/VolcTrain/internal/system/service"
	"github.com/GoSimplicity/VolcTrain/internal/user/api"
	dao2 "github.com/GoSimplicity/VolcTrain/internal/user/dao"
	service2 "github.com/GoSimplicity/VolcTrain/internal/user/service"
	"github.com/GoSimplicity/VolcTrain/pkg/utils"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/hibiken/asynq"
)

import (
	_ "github.com/google/wire"
)

// Injectors from wire.go:

func ProvideCmd() *Cmd {
	cmdable := InitRedis()
	handler := utils.NewJWTHandler(cmdable)
	logger := InitLogger()
	db := InitDB()
	roleDAO := dao.NewRoleDAO(db)
	roleService := service.NewRoleService(roleDAO, logger)
	v := InitMiddlewares(handler, logger, roleService)
	userDAO := dao2.NewUserDAO(db, logger)
	userService := service2.NewUserService(userDAO, roleService, logger)
	userHandler := api.NewUserHandler(userService, handler)
	apiDAO := dao.NewApiDAO(db, logger)
	apiService := service.NewApiService(logger, apiDAO)
	apiHandler := api2.NewApiHandler(apiService)
	roleHandler := api2.NewRoleHandler(roleService)
	engine := InitGinServer(v, userHandler, apiHandler, roleHandler)
	server := InitAsynqServer()
	cmd := &Cmd{
		Server: engine,
		Asynq:  server,
	}
	return cmd
}

// wire.go:

type Cmd struct {
	Server *gin.Engine
	Asynq  *asynq.Server
}

var HandlerSet = wire.NewSet(api2.NewRoleHandler, api2.NewApiHandler, api.NewUserHandler)

var ServiceSet = wire.NewSet(service2.NewUserService, service.NewApiService, service.NewRoleService)

var DaoSet = wire.NewSet(dao2.NewUserDAO, dao.NewRoleDAO, dao.NewApiDAO)

var UtilSet = wire.NewSet(utils.NewJWTHandler)

var Injector = wire.NewSet(
	InitMiddlewares,
	InitGinServer,
	InitLogger,
	InitRedis,
	InitDB,
	InitViper,
	InitAsynqClient,
	InitAsynqServer,
	InitScheduler, wire.Struct(new(Cmd), "*"),
)
