// Code generated by MockGen. DO NOT EDIT.
// Source: ../../pkg/database/mysql.go
//
// Generated by this command:
//
//	mockgen -source=../../pkg/database/mysql.go -destination=database_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
