// Code generated by MockGen. DO NOT EDIT.
// Source: ../../pkg/auth/jwt.go
//
// Generated by this command:
//
//	mockgen -source=../../pkg/auth/jwt.go -destination=jwt_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
