// Code generated by MockGen. DO NOT EDIT.
// Source: ../../pkg/database/redis.go
//
// Generated by this command:
//
//	mockgen -source=../../pkg/database/redis.go -destination=redis_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
