server:
  port: "9999"
log:
  dir: "./logs"
  level: "debug"
jwt:
  key1: "ebe3vxIP7sblVvUHXb7ZaiMPuz4oXo0l"
  key2: "ebe3vxIP7sblVvUHXb7ZaiMPuz4oXo0z"
  issuer: "K5mBPBYNQeNWEBvCTE5msog3KSGTdhmx"
  expiration: 3600
redis:
  addr: "localhost:6379"
  password: "v6SxhWHyZC7S"
mysql:
  addr: "root:root@tcp(localhost:3306)/volctrain?charset=utf8mb4&parseTime=True&loc=Local"
mock:
  enabled: true # 是否开启mock
