apiVersion: v2
name: volctrain
description: AI训练调度平台 Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - training
  - kubernetes
  - gpu
  - scheduling
maintainers:
  - name: VolcTrain Team
    email: dev@volctrain.com
sources:
  - https://github.com/volctrain/volctrain
home: https://volctrain.com